# Generated by Django 5.0.4 on 2024-04-30 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_singlepost_author_alter_singlepost_creation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlepost',
            name='creation_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 4, 30, 22, 36, 34, 871889), editable=False, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=192, verbose_name='Название')),
                ('short_desc', models.CharField(max_length=512, verbose_name='Краткое описание')),
                ('theme', models.CharField(choices=[('AL', 'Инопланетная жизнь'), ('CU', 'Таинственные культы'), ('GV', 'Правительственный заговор'), ('IL', 'Заговор иллюминатов'), ('RI', 'Мировая элита'), ('00', 'Неспецифический заговор')], db_default='00', default='Неспецифический заговор', max_length=32, verbose_name='Тематика')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 36, 34, 871889), verbose_name='Создание')),
                ('active', models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 36, 34, 871889), verbose_name='Последняя активность')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'форумная публикация',
                'verbose_name_plural': 'форумные публикации',
                'db_table': 'threads',
                'ordering': ['-created', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 4, 30, 22, 36, 34, 871889), verbose_name='Создание')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('homethread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.thread', verbose_name='Форум')),
            ],
            options={
                'verbose_name': 'комментарий форума',
                'verbose_name_plural': 'комментарии форума',
                'db_table': 'thread_comments',
                'ordering': ['created'],
            },
        ),
    ]
