# Generated by Django 5.0.4 on 2024-05-11 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_thread_options_alter_singlepost_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (1)'),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (2)'),
        ),
        migrations.AddField(
            model_name='singlepost',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (3)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (1)'),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (2)'),
        ),
        migrations.AddField(
            model_name='threadcomment',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка (3)'),
        ),
        migrations.AlterField(
            model_name='singlepost',
            name='creation_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 5, 11, 16, 36, 17, 855180), editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 36, 17, 856177), verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 36, 17, 856177), verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='threadcomment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 36, 17, 856177), verbose_name='Создание'),
        ),
    ]
